#!/bin/sh

NC='\033[0m'
BOrange='\033[48;5;202;97m'
BRed='\033[1;97;41m'

NAME=$(git branch | grep '*' | sed 's/* //')
echo "Running pre-push hook on: ${BOrange}" $NAME "${NC}"

echo "${BOrange}1. PHP Mess Detector${NC}"
php ./vendor/bin/phpmd app text ./phpmd.xml

STATUS_CODE=$?
if [ $STATUS_CODE -ne 0 ]; then
    echo "${BRed}1.... PHP Mess Detector${NC}"
    exit 1
fi

echo "${BOrange}2. PHP Code Sniffer${NC}"
php ./vendor/bin/phpcs --standard=phpcs.xml

STATUS_CODE=$?
if [ $STATUS_CODE -ne 0 ]; then
    echo "${BRed}2.... PHP Code Sniffer${NC}"
    exit 1
fi

echo "${BOrange}3. Laravel Pint${NC}"
php ./vendor/bin/pint --test

STATUS_CODE=$?
if [ $STATUS_CODE -ne 0 ]; then
    echo "${BRed}3.... Laravel Pint${NC}"
    exit 1
fi

echo "${BOrange}4. Running Tests${NC}"
php artisan test --parallel

STATUS_CODE=$?
if [ $STATUS_CODE -ne 0 ]; then
    echo "${BRed}5.... Running Tests${NC}"
    exit 1
fi

